apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Api cerc
  description: Api de consulta e alteração de dados de usuários
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: user:guest
